import json
from typing import List,Dict
from crewai_tools import BaseTool
from pydantic import BaseModel,Field
from langchain.tools import tool

GLOBAL_MEMORY:List[Dict]=[]

class StoreInput(BaseModel):
    model_name:str=Field(...,description="Name of the model")
    model_url: str = Field(..., description="URL of the model")
    readme_segment:str=Field(..., description="The documentation segment generated by Writer")
    test_log: str = Field(..., description="The verification log generated by QA")
    summary_note: str = Field(default="", description="Any extra notes from the agent")

class MemoryStoreTool(BaseTool):
    @tool("Stores processed model data into a shared memory for later merging.\
        Input should be clean, structured information extracted by you (the LLM).\
        Ensure model_name and model_url are accurate.")
    def store_memory(model_name:str,model_url:str,readme_segment:str,test_log:str,summary_note:str):
        GLOBAL_MEMORY.append({
            "model_name":model_name,
            "model_url":model_url,
            "readme_segment":readme_segment,
            "test_log":test_log,
            "summary_note":summary_note
        })
        return f"Successfully stored data for {model_name}. Total items in memory: {len(GLOBAL_MEMORY)}"
